// <auto-generated />
using System;
using CarStatistics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarStatistics.Data.Migrations
{
    [DbContext(typeof(CarStatisticsDbContext))]
    partial class CarStatisticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("CarStatistics.Core.models.CarSpeedStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarRegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CarSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CarSpeedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarSpeedStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
